baseURL = 'https://moosa-ebit.github.io/'
languageCode = 'en-us'
title = 'eBit Site'
theme = 'terminal'

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20

[params]
    readMore = "Read more"
    centerTheme = true
    missingBackButtonLabel = "Back to home page"
    description = "This site is for testing purposes only."
[params.logo]
    logoText = "eBit Site"
 
 